#Config file for DeepLidar

#Data generation - the number of workers for dask session
num_hipergator_workers: 25
training_csvs:
  - SJER
  - TEAK
kernel_size: 11
#Keras
workers: 1
use_multiprocessing: False
max_queue_size: 20
num_GPUs: 2
save_image_path: /orange/ewhite/b.weinstein/retinanet/
save_snapshot_path: /orange/ewhite/b.weinstein/retinanet/

#Sliding Window Size and Ovelap
patch_size: 400
patch_overlap: 0.05
rgb_res: 0.1

#Preprocessing routines
preprocess:
  zero_area: True

#Select sites
hand_annotation_site:
  - SJER
pretraining_site:
  - SJER
evaluation_site:
  - SJER

#Training
training_images: All
weights: None
imagenet_weights: False
batch_size: 20
epochs: 10
backbone: resnet50
shuffle_training: False
score_threshold: 0.20

#Evaluation
evaluation_images: 50
shuffle_evaluation: False
validation_percent: 5 #For hand annotation neon_MAP

#Non-max suppression, threshold for the IoU value to determine when a box should be suppressed.
nms_threshold: 0.1

#LIDAR density
min_density: 2

#Data Paths
SJER:
  h5: /orange/ewhite/b.weinstein/training_h5s/fourchannel/SJER/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/training/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/SJER/2018/
  training:
    RGB: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP3.30010.001/2018/FullSite/D17/2018_SJER_3/L3/Camera/Mosaic/V01/
    LIDAR: /ufrc/ewhite/b.weinstein/NeonData/SJER/DP1.30003.001/2018/FullSite/D17/2018_SJER_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/SJER/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/SJER/plots/
TEAK:
  h5: /orange/ewhite/b.weinstein/training_h5s/fourchannel/TEAK/
  training_csvs: /home/b.weinstein/TreeSegmentation/analysis/Results/detection_boxes/TEAK/2018/
  hand_annotations:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/training/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/training/ 
  training:
    RGB: /orange/ewhite/NeonData/TEAK/DP3.30010.001/2018/FullSite/D17/2018_TEAK_3/L3/Camera/Mosaic/V01/
    LIDAR: /orange/ewhite/NeonData/TEAK/DP1.30003.001/2018/FullSite/D17/2018_TEAK_3/L1/DiscreteLidar/ClassifiedPointCloud/
  evaluation:
    RGB: /home/b.weinstein/DeepLidar/data/TEAK/plots/
    LIDAR: /home/b.weinstein/DeepLidar/data/TEAK/plots/
